- library/src/main/java/com/google/android/exoplayer/Ac3PassthroughAudioTrackRenderer.java
- library/src/main/java/com/google/android/exoplayer/MediaCodecAudioTrackRenderer.java
- library/src/main/java/com/google/android/exoplayer/audio/AudioTrack.java
- Target 4x the minimum specified by the framework.
- Impose a minimum duration (250ms).
- Impose a maximum duration (750ms, or the minimum
specified by the framework if that's larger).
I've removed the ability to specify the multiplication
factor, since the underlying implementation is getting more
complicated, and we should really be able to figure this out
internally.
> Refine logic for determining AudioTrack size.

- library/src/main/java/com/google/android/exoplayer/util/BitArray.java
To reproduce the issue, you can use the data: `0x00 0x01 0xe1 0x90` to create the BitArray, then:
```java
buffer.skipBits(19);
int value = buffer.readBits(13);
```
The expected value is `400 (0x0190)`, but the returned value is `8080 (0x1F90)`
The root cause is in `BitArray.readUnsignedByte()`, it uses signed right shift, so the high bits are all 1 if the byte is a negative value.
The fix is simply to make it unsigned right shift.
> Fix a signed right shift issue in BitArray.readUnsignedByte()

- library/src/main/java/com/google/android/exoplayer/hls/HlsPlaylistParser.java
Previous regular expression for extracting codec information was wrong,
given a line that defines a variant it added information from “CODEC=“
text to the end of the line (including also information about
RESOLUTION or alternate rendition groups as part of the CODEC field).
This is not causing a functional problem (at least known by me)
although is making codecs field storing information that is not related
with the codec.
> Issue with regular expression for CODEC attribute

- library/src/main/java/com/google/android/exoplayer/hls/HlsChunkSource.java
Added an expiration time field to playlists blacklisted to allow
Exoplayer to continue playback when playlists that failed were
recovered from a bad state.
In live environments, some times occur that primary encoder stop
working for a while. In that cases, HLS failover mechanism in the
player should detect the situation and “switch” to playlists served by
the backup encoder (in case a backup encoder exists). This was well
managed before these changes.
However, and to ensure a playback experience that can recover itself
from temporary issues, we cannot blacklist a playlist forever. When
streaming live events using HLS, it is quite typical that the player
needs to switch from primary to backup playlists, and from backup to
primary ones, from time to time to have playback working when …
> Better management of blacklisted playlists

- demo/src/main/java/com/google/android/exoplayer/demo/Samples.java
- library/src/main/java/com/google/android/exoplayer/metadata/GeobMetadata.java
- library/src/main/java/com/google/android/exoplayer/metadata/Id3Parser.java
- library/src/main/java/com/google/android/exoplayer/metadata/PrivMetadata.java
- Added support for ID3 frames of types GEOB and PRIV.
- GEOB type is commonly used by dynamic ads providers to include in the
stream information about the ads to be played.
- PRIV type is commonly used for time synchronization (example:
synchronizing playback of a live stream and its webvtt captions) and
also by analytics companies to include tracking information in the
stream.
- Added a sample stream from Apple that contains ID3 metadata.
> Added support for new types of ID3 frames

- library/src/main/java/com/google/android/exoplayer/hls/HlsPlaylistParser.java
As per http://tools.ietf.org/html/draft-pantos-http-live-streaming-04#section-5.2,
the initializaton vector (IV) of the AES decryption algorithm should be set to:
- the IV attribute value if present,
- the sequence number otherwise.
Currently, the IV is set once and use over all next media sequences
where the IV attribute is not set. The fix is to use the provided IV if
given or use the current media sequence number.
> Fix AES decryption of HLS streams.

- library/src/main/java/com/google/android/exoplayer/MediaCodecTrackRenderer.java
* this fixes a bug when switching from HE-AAC 22050Hz to AAC 44100Hz (the AudioTrack was not reset and we were trying to send a bad number of bytes, triggering a "AudioTrack.write() called with invalid size" error)
* this also improves quality switches, making it almost seamless
> better handling of input format change for non-adaptive codecs

- library/src/main/java/com/google/android/exoplayer/upstream/DataSourceInputStream.java
Currently, read() returns garbage data when EOF is reached. Ideally it should return -1 if EOF is reached.
> Fix DataSourceInputStream.read() for EOF cases

- library/src/main/java/com/google/android/exoplayer/upstream/ContentDataSource.java
In android, content-uri is widely used.
For example, "content://download/" , "content://media/external/video" and so on.
We can query the file descriptor from content resolver and create the input stream from it.
> support content uri (e.q. content://xxx)

- library/src/main/java/com/google/android/exoplayer/hls/HlsExtractorWrapper.java
Fixes issue where an NPE occurs when RollingSampleBuffer is created
with a null Allocator.
> HLS AAC fix

- demo/src/main/java/com/google/android/exoplayer/demo/player/ExtractorRendererBuilder.java
- library/src/main/java/com/google/android/exoplayer/MediaFormat.java
- library/src/main/java/com/google/android/exoplayer/extractor/mp4/Atom.java
- library/src/main/java/com/google/android/exoplayer/extractor/mp4/AtomParsers.java
- library/src/main/java/com/google/android/exoplayer/extractor/mp4/Mp4Extractor.java
- library/src/main/java/com/google/android/exoplayer/text/tx3g/SubtitleData.java
- library/src/main/java/com/google/android/exoplayer/text/tx3g/TextParser.java
- library/src/main/java/com/google/android/exoplayer/text/tx3g/TextSubtitle.java
- library/src/main/java/com/google/android/exoplayer/util/MimeTypes.java
Atom "tx3g" is for text-based subtitle. Android MediaPlayer has support this format.
We can use [Mp4box](http://gpac.wp.mines-telecom.fr/mp4box/) of [QuickTimePro](https://developer.apple.com/library/mac/documentation/QuickTime/QT6_3/Chap1/QT6WhatsNew.html) to encode the SRT into the a MP4 file.
> parse mp4 tx3g

- library/src/main/java/com/google/android/exoplayer/text/subrip/SubripCue.java
- library/src/main/java/com/google/android/exoplayer/text/subrip/SubripParser.java
- library/src/main/java/com/google/android/exoplayer/text/subrip/SubripSubtitle.java
- library/src/main/java/com/google/android/exoplayer/util/MimeTypes.java
- library/src/test/assets/subrip/typical
- library/src/test/java/com/google/android/exoplayer/text/subrip/SubripParserTest.java
For details on SRT, see http://en.wikipedia.org/wiki/SubRip
Still missing in this PR is support for x1,x2,y1,y2 coordinate parsing.
@ojw28 seeking your advice on the required data model changes. `Cue` could probably have traits like `Positionable` (SRT) or `Alignable` (for WebVTT) or `ImageRepresentable` (for SDH, at a later stage?).
> Subrip (SRT) support

- library/src/main/java/com/google/android/exoplayer/extractor/webm/WebmExtractor.java
This extends the current capabilities of the WebM extractor to allow HEVC (h265) video. I've included a duplicated version of `AtomParsers.parseAvcCFromParent` which isn't great, but is consistent with the current H264 implementation.
If required, I can provide sample files to test, but most of those can also be easily found via a very quick Google.
> Add support for HEVC video in Matroska files

- library/src/main/java/com/google/android/exoplayer/hls/HlsPlaylistParser.java
HLS is allowed format like `#EXT-X-KEY:METHOD=AES-128,URI="https://example.com/aes.m3u8key",IV=0xaaaaaaaaaaaaaaaaaaaaaaaaaaa,KEYFORMATVERSIONS="1"` .
`URI_ATTR + "=\"(.+)\"")` will match `URI="https://example.com/aes.m3u8key",IV=0xaaaaaaaaaaaaaaaaaaaaaaaaaaa,KEYFORMATVERSIONS="1"`
So, modify to `URI_ATTR + "=\"([^\"]+)\"")`
> Fixed bug of AES URI Pattern for hls

- library/src/main/java/com/google/android/exoplayer/drm/StreamingDrmSessionManager.java
Make it so that extensions of StreamingDrmSessionManager may override open/close.
I'm raising this concern as a PR. We are currently extending StreamingDrmSessionManager for the purpose of enabling preparations of drm sessions. I.e. opening sessions before they are actually used. This speeds up playback since license keys are fetched during this early stage. To do this, we were overriding open/close in StreamingDrmSessionManager (open in particular) to be able to close our prepare reference since open/close are counted. While bumping our version of ExoPlayer I realized these methods are now final. Unless there's a good reason to keep them final I would suggest making them overridable again.
> Enable override of open/close in StreamingDrmSessionManager

- library/src/main/java/com/google/android/exoplayer/text/subrip/SubripParser.java
I was testing SRT support when I found that a number of my test files didn't parse. It turned out the reason was that they contained additional empty lines before the next numeric counter. I don't think this is uncommon, and fairly easy to handle.
Here's an example of an SRT which includes this:
```
1
00:00:34,160 --> 00:00:35,366
Start simple.
2
00:00:35,440 --> 00:00:36,965
Start with what you know is true.
```
> Ignore extra returns in Subrip parsing

- library/src/main/java/com/google/android/exoplayer/util/ParsableBitArray.java
When I proguraded my app which play HLS movies, surely I encountered ArrayIndexOutOfBoundsException #748 by using 303SH(4.2.2), SH-01F(4.2.2), F-01F(4.2.2) and other 4.2.2 devices.
I logged ParsableBitArray.readBits as below:
```
public int readBits(int n) {
Log.d("point1", String.valueOf(n) + " : " + String.valueOf(byteOffset));
if (n == 0) {
return 0;
}
int returnValue = 0;
// While n >= 8, read whole bytes.
while (n >= 8) {
int byteValue;
if (bitOffset != 0) {
byteValue = ((data[byteOffset] & 0xFF) << bitOffset)
| ((data[byteOffset + 1] & 0xFF) >>> (8 - bitOffset));
} else {
byteValue = data[byteOffset];
}
n -= 8;
returnValue |= (byteValue & 0xFF) << n;
byteOffset++;
}
Log.d("point2", String.valueOf(n) + " : " + String.valueOf(byteOffset));
```
At the crash case, unexpected values were …
> Prevent ArrayIndexOutOfBoundsException when proguard is enabled

- library/src/androidTest/assets/webvtt/typical_with_comments
- library/src/androidTest/assets/webvtt/typical_with_metadata
- library/src/androidTest/java/com/google/android/exoplayer/text/webvtt/WebvttParserTest.java
- library/src/main/java/com/google/android/exoplayer/text/webvtt/WebvttParser.java
- Line parameter
- Added support for value and line alignment attributes.
- Support negative numbers when line is an absolute number (not a
percentage).
- Position parameter
- Added support for value and position alignment attributes
- Added support for WebVTT comment blocks
- Percentage values now accept decimal numbers (as webvtt spec states)
- Added new WebVTT tests for testing all new implemented features
This PR is focused on improving the parser. Later work is needed on improving WebVTT cue rendering process to use new parsed parameters (line alignment, position alignment, line as percentage, etc)
> Improve WebVTT parser according to WebVTT spec

- library/src/main/java/com/google/android/exoplayer/dash/mpd/MediaPresentationDescriptionParser.java
Only parse the `value` as Int when the `schemeIdUri` is `urn:mpeg:dash:23003:3:audio_channel_configuration:2011`
For example this stream contains Dolby audio tracks which follow a different scheme: http://demo.cf.castlabs.com/media/TOS/abr/Manifest.mpd
Example:
`<AudioChannelConfiguration schemeIdUri="urn:dolby:dash:audio_channel_configuration:2011" value="A000"/>`
For that case the `audioChannel` is set to -1, as the Format class expects when it is not applicable.
> Parse audioChannels only when on mpeg-dash

- library/src/main/java/com/google/android/exoplayer/drm/StreamingDrmSessionManager.java
This adds a callback for when the DRM session is ready.
I.e. when keys required for decryption has been acquired.
-----
We have the need of getting notified when DRM session has been successfully loaded and ready to be used. Therefore, I suggest an addition to StreamingDrmSessionManager's EventListener. Do you think it makes sense?
> Add onDrmSessionReady callback

- library/src/main/java/com/google/android/exoplayer/extractor/webm/WebmExtractor.java
- library/src/main/java/com/google/android/exoplayer/util/MimeTypes.java
This change adds support for mpeg2 decoding on devices like the Nvidia Shield.
> Add support for MPEG2 video codec in WebMExtractor

- library/src/main/java/com/google/android/exoplayer/extractor/webm/WebmExtractor.java
- library/src/main/java/com/google/android/exoplayer/util/MimeTypes.java
The Nvidia Shield recently added support for TrueHD passthrough. In order to fully implement that support, it requires using non-official AudioFormat encodings which is why I wouldn't suggest using it here. However, the implementation for extracting TrueHD audio from an MKV is still valid and may be useful for any device which can natively decode it. Hence why I thought i'd submit this PR.
> Add support for TrueHD audio codec in WebMExtractor

- library/src/main/java/com/google/android/exoplayer/hls/HlsChunkSource.java
- library/src/main/java/com/google/android/exoplayer/hls/HlsPlaylistParser.java
- library/src/main/java/com/google/android/exoplayer/hls/Variant.java
For the same usecase as mentioned in: https://github.com/google/ExoPlayer/pull/884 we needed to parse the `NAME` label from the HlsMasterPlaylist and have it available in the `variants` array.
CLA should be signed: https://groups.google.com/forum/#!forum/jwplayer-google-contributors
Feel free to ask questions, feedback is appreciated.
Thanks.
> Parse HLS NAME label from the MasterPlaylist

- library/src/main/java/com/google/android/exoplayer/smoothstreaming/SmoothStreamingManifestParser.java
This is necessary to avoid parsing errors when playing Smooth Streaming content with DTS or Dolby audio tracks.
> Added missing MimeTypes to Smooth Streaming manifest parser

- library/src/main/java/com/google/android/exoplayer/text/ttml/TtmlRenderUtil.java
Multiple identical TTML fontStyles or fontWeights or textDecorations
on the content for a specific moment were rendered as if there's only
one decoration (span).
That's because SpannableStringBuilder.setSpan(span, start, end, flag)
found an earlier set span (the static allocated span's reference
is the same each time) and only refreshed this first span's start and
end values instead of adding a new span at its (new) different range.
This patch removes the static data members;
this makes the newly allocated span objects distinguishable.
A correct implementation is favoured over worries about memory
consumption.
> Allow multiple identical but intermittent spans

- library/src/main/java/com/google/android/exoplayer/extractor/ts/TsExtractor.java
- library/src/main/java/com/google/android/exoplayer/util/Ac3Util.java
These changes:
- Add support to identify a number of audio stream types via the descriptor tag in MPEGTS
- Modify (fix?) the way EAC3 sync frame format was parsed
The following is the set of descriptor tags used by ffmpeg:
```c++
static const StreamType DESC_types[] = {
{ 0x6a, AVMEDIA_TYPE_AUDIO,    AV_CODEC_ID_AC3          }, /* AC-3 descriptor */
{ 0x7a, AVMEDIA_TYPE_AUDIO,    AV_CODEC_ID_EAC3         }, /* E-AC-3 descriptor */
{ 0x7b, AVMEDIA_TYPE_AUDIO,    AV_CODEC_ID_DTS          },
{ 0x56, AVMEDIA_TYPE_SUBTITLE, AV_CODEC_ID_DVB_TELETEXT },
{ 0x59, AVMEDIA_TYPE_SUBTITLE, AV_CODEC_ID_DVB_SUBTITLE }, /* subtitling descriptor */
{ 0 },
};
```
After I made the change to handle the descriptor tags, I found that ExoPlayer still didn't like the EAC3 MPEGTS files output by FFMPEG. Upon …
> Improve identification of (E)AC3 content in MPEGTS and tweak EAC3 parsing

- library/src/main/java/com/google/android/exoplayer/text/ttml/TtmlColorParser.java
The TTML 1 spec. defines an exact RGBA color tuple as #rrggbbaa
See https://www.w3.org/TR/ttml1/#style-value-color
Android's internal representation is ARGB.
The correct parsing therefore requires a bit of extra byte shuffling ...
> Fix RGBA color tuple parsing

- library/src/main/java/com/google/android/exoplayer/upstream/UdpDataSource.java
Current implementation doesn't work at least for udp://@239.0.1.2:1234, moreover parsing is already done by Uri
> UdpDataSource: use Uri's methods to access host, port parts

- library/src/main/java/com/google/android/exoplayer/MediaFormat.java
- library/src/main/java/com/google/android/exoplayer/extractor/webm/WebmExtractor.java
- library/src/main/java/com/google/android/exoplayer/util/MimeTypes.java
This change adds identification of PGS/VobSub tracks to MKV. With this inclusion, it's possible for applications to provide their own `TrackRenderer`s in order to handle these MimeTypes.
You'll notice that VobSub requires us to later consume the `codecPrivate` data. As mentioned by the spec (https://www.matroska.org/technical/specs/subtitles/images.html), in the case for VobSub, this contains the IDX manifest.
> Add support to identify VobSub/PGS tracks from MKV

- library/src/main/java/com/google/android/exoplayer/extractor/webm/WebmExtractor.java
- library/src/main/java/com/google/android/exoplayer/util/MimeTypes.java
Shield TV supports VC1 hardware decoding.  This allows Exoplayer to use the decoder for MKV files with VC1.
> Fourcc vc1 metadata parse support

- library/src/main/java/com/google/android/exoplayer/extractor/webm/WebmExtractor.java
Seems that 1 or 2 channel tracks come in directly as PCM_INT_LIT while >2 channel tracks are wrapped in MS ACM to preserve channel mapping.
> Add 16 bit PCM audio track detected including MS ACM for >2 channels 

- library/src/main/java/com/google/android/exoplayer/hls/HlsPlaylistParser.java
The http live streaming draft(https://www.ietf.org/id/draft-pantos-http-live-streaming-19.txt) specifies that the EXT-X-ENDLIST may appear anywhere in the media playlist file. In case of ExoPlayer's HlsPlaylistParser's parseMediaPlaylist() would stop parsing the file when the end list tag is found due to the break statement. The end list tag may appear anywhere if the break statement is removed.
> Remove break statement when end list tag found by hls playlist parser
